# Docker compose for development purposes only
version: "3"
services:
  shiori:
    build:
      context: .
      dockerfile: Dockerfile.compose
    container_name: shiori
    ports:
      - "8080:8080"
    volumes:
      - "./dev-data:/srv/shiori"
      - ".:/src/shiori"
    restart: unless-stopped